package org.endoqa.fastly.util

/**
 * Generated by Copilot, no safe guarantees
 * TODO: add a cache?
 */
fun calculateVarIntSize(int: Int): Int {

    var value = int
    var size = 0
    while (true) {
        value = value ushr 7
        size++
        if (value == 0) {
            return size
        }
    }
}
